/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20). https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */

package br.com.zup.dtp.api.restclient;

import br.com.zup.dtp.api.dto.LanguageDTO;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Api(value = "Name", description = "the Name API")
public interface NameApi {

   @ApiOperation(value = "Find programming language by name", nickname = "getLanguageByName", notes = "Returns a single programming language",
       response = LanguageDTO.class, authorizations = { @Authorization(value = "api_key") }, tags = { "name", })
   @ApiResponses(value = { @ApiResponse(code = 200, message = "successful operation", response = LanguageDTO.class),
                           @ApiResponse(code = 400, message = "Invalid Name"), @ApiResponse(code = 404, message = "Language not found") })
   @RequestMapping(value = "/language/{name}", produces = "application/json", method = RequestMethod.GET)
   ResponseEntity<LanguageDTO> getLanguageByName(@ApiParam(value = "Name of Language to return", required = true) @PathVariable("name") String name);

}
